version: "3.7"

services:
  web:
    build: ./microblog
#    image: microblog:latest
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
    networks:
      - backend
#    volumes:
#      - ./microblog/:/usr/code/microblog

  db:
    image: mysql:5.7
#    env_file:
#      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

    networks:
      - backend
#    volumes:
#      - dbdata:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata: